### ISSUE TITLE
绘图错误

### ISSUE THREAD

**Issue by HoshinoTented** [mzdluo123/MineSweeper#1]
![TIM图片20200628220259.jpg](https://i.loli.net/2020/06/28/Civ3RznAkXgZB8j.jpg)
`CE` 格应当为数字（非雷），但图中绘制为未知格，并且 `m d c e` 时反馈非法位置

**Comment by mzdluo123** [comment]
应该使用m d ce
对于是不是应该直接显示数字还需要再优化一下
