### ISSUE TITLE
?不是 这直接把库拉过来了啊(笑哭)

### ISSUE THREAD

**Issue by GreyElaina** [mzdluo123/MineSweeper#2]
如题...

**Comment by mzdluo123** [comment]
是的，因为你的pypi上的包有问题，并且从内存发图有个bug我修了一下

如果还继续维护的话我可以pr过去

**Comment by GreyElaina** [comment]
你可以往 Graia Project 的那个 graia-protocol-mirai-aiohttp PR吗?

**Comment by mzdluo123** [comment]
可以的吧，但是我得先看看代码
